In [1]:
import pandas as pd

In [5]:
import pandas as pd

# 1. Create a list of all the season strings.
seasons = [f"season-{i}{i+1}" for i in range(9, 20)]  # Generates season-0910, season-1011, ..., season-1910

dataframes = []

for season in seasons:
    # 2. Construct filename based on season string.
    filename = f'spanish-la-liga_zip/data/{season}_csv.csv'
    
    try:
        # 3. Read the CSV file into a dataframe.
        temp_df = pd.read_csv(filename)
        temp_df['season'] = season 
        
        # 4. Append the dataframe to the list.
        dataframes.append(temp_df)
    except FileNotFoundError:
        print(f"File for {season} not found!")

# 5. Concatenate all dataframes in the list.
df = pd.concat(dataframes, ignore_index=True)

File for season-910 not found!
File for season-1920 not found!

In [6]:
columns_to_keep = ['season','HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'HTHG', 'HTAG', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC']
df = df[columns_to_keep]

In [8]:
df.rename(columns={
    'FTHG': 'FullTime_HomeGoals',
    'FTAG': 'FullTime_AwayGoals',
    'HTHG': 'HalfTime_HomeGoals',
    'HTAG': 'HalfTime_AwayGoals',
    'HST': 'Home_ShotsOnTarget',
    'AST': 'Away_ShotsOnTarget',
    'HF': 'Home_Fouls',
    'AF': 'Away_Fouls',
    'HC': 'Home_Corners',
    'AC': 'Away_Corners'
}, inplace=True)

In [9]:
df

,season,HomeTeam,AwayTeam,FullTime_HomeGoals,FullTime_AwayGoals,HalfTime_HomeGoals,HalfTime_AwayGoals,Home_ShotsOnTarget,Away_ShotsOnTarget,Home_Fouls,Away_Fouls,Home_Corners,Away_Corners
0,season-1011,Hercules,Ath Bilbao,0,1,0,0,3,5,15,18,10,1
1,season-1011,Levante,Sevilla,1,4,1,2,4,8,20,22,4,2
2,season-1011,Malaga,Valencia,1,3,1,1,5,8,16,15,7,10
3,season-1011,Espanol,Getafe,3,1,1,0,8,1,17,9,8,4
4,season-1011,La Coruna,Zaragoza,0,0,0,0,2,3,16,19,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,season-1819,Levante,Ath Madrid,2,2,2,0,7,8,9,7,6,4
3416,season-1819,Sevilla,Ath Bilbao,2,0,1,0,3,1,14,19,2,3
3417,season-1819,Valladolid,Valencia,0,2,0,1,4,6,12,10,8,2
3418,season-1819,Eibar,Barcelona,2,2,2,2,8,3,11,3,5,2
3419,season-1819,Real Madrid,Betis,0,2,0,0,2,7,17,11,1,5